?<div style="text-align: center; padding: 20px; font-family: Vazir;">
<h1 align="center" style="font-size: 28px; color:rgb(64, 244, 202); width: 100%;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>تمرین 4<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1>
<h2 style="color:rgb(90, 255, 184); font-size: 20px;">Comparing BART and GPT-2 for Text-to-SQL</h2>
<p align="center" style="color: #666; font-size: 16px;">زهرا فیض اله زاده</p>
<p align="center" style="color: #666; font-size: 16px; margin-bottom: 30px;">zahra.feizolahzadeh@gmail.com</p>

<div dir="rtl" style="border: 2px dashed rgb(90, 255, 184); border-radius: 8px; padding: 20px; margin: 20px auto; max-width: 500px; text-align: right;">
<p style="color: rgb(64, 244, 202); font-size: 18px; margin-bottom: 15px;">📝 مشخصات دانشجو:</p>
<p style="color: #666; margin: 5px;">نام و نام خانوادگی: سید مانی میرشعبانی</p>
<p style="color: #666; margin: 5px;">شماره دانشجویی: ۸۱۰۸۰۱۰۸۰</p>
<p style="color: #666; margin: 5px;">تاریخ ارسال: {{تاریخ_ارسال}}</p>
</div>
</div>

<div dir="rtl" style="border: 2px solid #f0ad4e; background-color: #fffbe6; border-radius: 8px; padding: 20px; margin: 20px auto; width: 90%; text-align: justify; font-family: Vazir, sans-serif; color: #333; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
    <p style="font-weight: bold; margin-bottom: 15px; color: #d9534f; font-size: 1.1em;">
        ⚠️ توضیح در خصوص استفاده از دستیار هوش مصنوعی:
    </p>
    <p style="line-height: 1.8;">
        این تمرین با کمک دستیار هوش مصنوعی <strong>Gemini</strong> انجام شده است و مشروح مکالمه از طریق این لینک قابل مشاهده است:
        <a href="https://gemini.google.com/share/2ea23d55bd57" target="_blank" style="color: #0275d8; text-decoration: none; font-weight: bold;">(لینک)</a>.
        <br><br>
        در تمامی مراحل، حالت <strong>«Guided Learning»</strong> فعال بوده و صرفاً جهت بررسی خطاها (Error Checking) مورد استفاده قرار گرفته است.
        همچنین از این ابزار برای ویرایش و زیباسازی قالب‌بندی (Markup) استفاده شده است؛ بدین صورت که متن اصلی مارک‌آپ‌ها توسط خودم به زبان انگلیسی نگارش شده و سپس جهت ساختاردهی صحیح مارک‌داون و نمایش مناسب، توسط هوش مصنوعی ویرایش شده‌اند.
    </p>
</div>


<div dir="rtl" style="text-align: justify; padding: 25px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
<div style="line-height: 2.0; font-size: 17px; color: black; font-family: Vazir;">
<div style="padding-right:40px">
</div>
<br>
<div style="padding-right:100px">
📋 <b>ساختار تمرین:</b>
<br>
<li><b>سوال اول - <span dir="ltr">Text-to-SQL with BART and GPT-2</span> (50)</b></li>
<ul>
<li>بخش اول: بارگذاری و پیش‌پردازش داده‌های Text-to-SQL</li>
<li>بخش دوم: آموزش مدل Encoder–Decoder (BART)</li>
<li>بخش سوم: آموزش مدل Decoder-only (GPT-2)</li>
<li>بخش چهارم: مقایسه و تحلیل نهایی</li>

</ul>

</div>
</div>
<div dir='rtl' style="line-height: 1.8; font-family: Vazir; font-size: 16px; margin-top: 20px; background-color: #e8eaf6; padding: 15px; border-radius: 8px; color:black">
💡 <b>نکات مهم:</b>
<br>
<li>	مسئله Text-to-SQL حساسیت بسیار بالایی به جزئیات دارد.</li>
کوچک‌ترین اختلاف در ساختار SQL، ترتیب کلیدواژه‌ها یا حتی فاصله‌ها می‌تواند باعث نامعتبر شدن خروجی شود. بنابراین هنگام ارزیابی، به‌ویژه در معیار Normalized EM، باید دقت زیادی به اصلاح فاصله‌ها، حذف سمیکالن اضافه، و یکسان‌سازی case کلمات داشته باشید تا مقایسه‌ای منصفانه انجام شود.
<li>	معماری‌های Encoder–Decoder و Decoder-only رفتارهای متفاوتی در تولید SQL دارند.</li>
ساخت صحیح ورودی‌ها (Prefix)، نحوه قرار دادن question و schema در متن، ترتیب tokenها،          padding مناسب و mask کردن بخش‌های غیرهدف، همگی نقش اساسی در عملکرد این مدل‌ها دارند. دقت کنید که GPT-2 باید تمام اطلاعات را در قالب یک توالی یکپارچه دریافت کند، درحالی‌که BART ورودی را رمزگذاری و سپس خروجی SQL را مستقل تولید می‌کند.
<li>	برای مقایسه مدل‌ها، آموزش حداقلی اما واقعی لازم است.</li>
باید حداقل یک ایپاک کامل روی حداقل بیست هزار نمونه از داده‌های آموزش اجرا شود تا مدل به‌طور معنی‌دار الگوهای اولیه Text-to-SQL را یاد بگیرد و ارزیابی‌ها قابل اعتماد باشند. لازم نیست آموزش طولانی انجام دهید، اما اجرای همین مقدار حداقلی برای تحلیل و مقایسه معماری‌ها ضروری است.
</div>
</div>

# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال دوم: تحلیل و مقایسه معماری‌های Encoder–Decoder و Decoder-Only در تسک Text-to-SQL <br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>

<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">
در این بخش از تمرین با مسئله Text-to-SQL آشنا می‌شوید؛ وظیفه‌ای که در آن مدل باید پرسش‌های زبان طبیعی را به کوئری SQL معتبر تبدیل کند. هدف تمرین، مقایسه عملی دو معماری مهم ترنسفورمری است: Encoder–Decoder‌ (مانند BART) و Decoder-only‌ (مانند GPT-2). پس از آماده‌سازی داده‌ها، ابتدا مدل BART و سپس مدل GPT-2 را برای این تسک آموزش می‌دهید و در نهایت عملکرد دو مدل را از نظر دقت، رفتار تولیدی و انواع خطاها تحلیل و مقایسه خواهید کرد.
</p>

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش اول: مجموعه‌داده و پیش‌پردازش(10 نمره)</div>

<div dir="rtl" style="text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
داده‌های Gretel Synthetic Text-to-SQL را از HuggingFace بارگذاری کرده و فایل‌های train/test را دریافت کنید. ساختار دیتاست را بررسی کرده، یک نمونه نمایش دهید و نقش ستون‌های اصلی از جمله question، schema و query را توضیح دهید. سپس داده‌ها را با استفاده از train_test_split به بخش‌های train و dev تقسیم کنید و ستون‌ها را به اسامی استاندارد (question، schema، query) تغییر دهید. برای کاهش زمان آموزش، روی هر بخش محدودیت اندازه تعیین کنید. در پایان، تحلیل کوتاهی از ماهیت پرسش‌ها، ساختار schemaها و چالش‌هایی که برای مدل ایجاد می‌کنند ارائه دهید.
</div>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
در پایان این بخش انتظار می‌رود دانشجو یک دیتافریم کاملا آماده برای مراحل بعدی در اختیار داشته باشد. خروجی مطلوب شامل بارگذاری صحیح فایل‌های train و test، نمایش ساختار کلی داده‌ها، تقسیم درست داده‌ها به بخش‌های train و dev، تغییر نام ستون‌ها به قالب استاندارد، و اعمال زیرنمونه‌گیری برای محدود کردن حجم داده‌ها است. علاوه بر این، باید یک نمونه واقعی از داده‌ها همراه با توضیح مختصر درباره ماهیت سؤال، ساختار schema و نمونه SQL نمایش داده شود تا مشخص شود داده‌ها به‌درستی پردازش شده و برای ورود به مراحل آموزش مدل آماده هستند.

</p>

First let's donwload the dataset and take a look at its structure.

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("gretelai/synthetic_text_to_sql")
train_data = dataset['train']
test_data = dataset['test']

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [3]:
print(dataset)
print(train_data.features)

DatasetDict({
    train: Dataset({
        features: ['id', 'domain', 'domain_description', 'sql_complexity', 'sql_complexity_description', 'sql_task_type', 'sql_task_type_description', 'sql_prompt', 'sql_context', 'sql', 'sql_explanation'],
        num_rows: 100000
    })
    test: Dataset({
        features: ['id', 'domain', 'domain_description', 'sql_complexity', 'sql_complexity_description', 'sql_task_type', 'sql_task_type_description', 'sql_prompt', 'sql_context', 'sql', 'sql_explanation'],
        num_rows: 5851
    })
})
{'id': Value('int32'), 'domain': Value('string'), 'domain_description': Value('string'), 'sql_complexity': Value('string'), 'sql_complexity_description': Value('string'), 'sql_task_type': Value('string'), 'sql_task_type_description': Value('string'), 'sql_prompt': Value('string'), 'sql_context': Value('string'), 'sql': Value('string'), 'sql_explanation': Value('string')}

In [4]:
print(train_data[0])
df = pd.DataFrame([train_data[0]])
display(df)

{'id': 5097, 'domain': 'forestry', 'domain_description': 'Comprehensive data on sustainable forest management, timber production, wildlife habitat, and carbon sequestration in forestry.', 'sql_complexity': 'single join', 'sql_complexity_description': 'only one join (specify inner, outer, cross)', 'sql_task_type': 'analytics and reporting', 'sql_task_type_description': 'generating reports, dashboards, and analytical insights', 'sql_prompt': 'What is the total volume of timber sold by each salesperson, sorted by salesperson?', 'sql_context': "CREATE TABLE salesperson (salesperson_id INT, name TEXT, region TEXT); INSERT INTO salesperson (salesperson_id, name, region) VALUES (1, 'John Doe', 'North'), (2, 'Jane Smith', 'South'); CREATE TABLE timber_sales (sales_id INT, salesperson_id INT, volume REAL, sale_date DATE); INSERT INTO timber_sales (sales_id, salesperson_id, volume, sale_date) VALUES (1, 1, 120, '2021-01-01'), (2, 1, 150, '2021-02-01'), (3, 2, 180, '2021-01-01');", 'sql': 'SELECT salesperson_id, name, SUM(volume) as total_volume FROM timber_sales JOIN salesperson ON timber_sales.salesperson_id = salesperson.salesperson_id GROUP BY salesperson_id, name ORDER BY total_volume DESC;', 'sql_explanation': 'Joins timber_sales and salesperson tables, groups sales by salesperson, calculates total volume sold by each salesperson, and orders the results by total volume in descending order.'}

,id,domain,domain_description,sql_complexity,sql_complexity_description,sql_task_type,sql_task_type_description,sql_prompt,sql_context,sql,sql_explanation
0,5097,forestry,Comprehensive data on sustainable forest manag...,single join,"only one join (specify inner, outer, cross)",analytics and reporting,"generating reports, dashboards, and analytical...",What is the total volume of timber sold by eac...,"CREATE TABLE salesperson (salesperson_id INT, ...","SELECT salesperson_id, name, SUM(volume) as to...","Joins timber_sales and salesperson tables, gro..."

As we can see, there are no question, schema and query columns! but their content can be found in other columns and just needs to be renamed!

Now let's rename the sql_prompt column to question, sqp_context to schema and sql to query and remove the rest of the columns

In [5]:
dataset = dataset.rename_columns({
    "sql_prompt": "question",
    "sql_context": "schema",
    "sql": "query"
})

dataset = dataset.select_columns(["question", "schema", "query"])

print(dataset)
print(dataset['train'][0])

DatasetDict({
    train: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 100000
    })
    test: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 5851
    })
})
{'question': 'What is the total volume of timber sold by each salesperson, sorted by salesperson?', 'schema': "CREATE TABLE salesperson (salesperson_id INT, name TEXT, region TEXT); INSERT INTO salesperson (salesperson_id, name, region) VALUES (1, 'John Doe', 'North'), (2, 'Jane Smith', 'South'); CREATE TABLE timber_sales (sales_id INT, salesperson_id INT, volume REAL, sale_date DATE); INSERT INTO timber_sales (sales_id, salesperson_id, volume, sale_date) VALUES (1, 1, 120, '2021-01-01'), (2, 1, 150, '2021-02-01'), (3, 2, 180, '2021-01-01');", 'query': 'SELECT salesperson_id, name, SUM(volume) as total_volume FROM timber_sales JOIN salesperson ON timber_sales.salesperson_id = salesperson.salesperson_id GROUP BY salesperson_id, name ORDER BY total_volume DESC;'}

For limiting the data as it is mentioned in the next section we will keep 20k data from train and 2.5k from test (which will later be splitted to test and dev sets)

In [6]:
random_seed = 24
dataset['train'] = dataset['train'].shuffle(seed=random_seed).select(range(20500))
dataset['test'] = dataset['test'].shuffle(seed=random_seed).select(range(2000))

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 20500
    })
    test: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 2000
    })
})

And finally let's split the data into train, dev and test dataset each having 20k, 500 and 2k data respectively

In [7]:
test_dev_split = dataset['train'].train_test_split(test_size=500, seed=random_seed)
dataset['train'] = test_dev_split['train']
dataset['dev'] = test_dev_split['test']

print(dataset)

print(dataset['train'][0])
df = pd.DataFrame([dataset['train'][0]])
display(df)

DatasetDict({
    train: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 20000
    })
    test: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 2000
    })
    dev: Dataset({
        features: ['question', 'schema', 'query'],
        num_rows: 500
    })
})
{'question': 'What is the average severity of vulnerabilities found in the last quarter, grouped by month?', 'schema': 'CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT);', 'query': "SELECT DATE_FORMAT(timestamp, '%Y-%m') as month, AVG(severity) as avg_severity FROM vulnerabilities WHERE timestamp >= NOW() - INTERVAL 3 MONTH GROUP BY month;"}

,question,schema,query
0,What is the average severity of vulnerabilitie...,"CREATE TABLE vulnerabilities(id INT, timestamp...","SELECT DATE_FORMAT(timestamp, '%Y-%m') as mont..."

<div dir='ltr' style='background:#fffbe6; font-family: sans-serif; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Answer:</b><br>
We have three main columns as stated in the question. Below is their role and analysis:

<b>1. Schema</b><br>
This defines the general structure of our database. It sets the types of each column, assigns their names, and gives the model a general idea about what kind of dataset it is dealing with. It is common practice to write the schema of each dataset for managing it, and it is absolutely necessary here; otherwise, the model really wouldn't know how to interact with it!

<b>2. Question</b><br>
The Question is our goal. It is what the user wants to achieve, written in natural human language. The goal of our model is to understand this intent and generate appropriate queries for it.

<b>3. Query</b><br>
This acts as our "gold" output. It is the correct SQL command that achieves the desired result. Our goal is to fine-tune the model so it can create such results.

<hr style="border-top: 1px dashed #f0ad4e;">

<b>Analysis of Challenges:</b>

* <b>Schema:</b> LLMs are mostly accustomed to human languages, but schemas are far from normal human language! We can see this by taking a look at the example above (<i>CREATE TABLE dishes...</i>). I imagine a major challenge would be to make the model understand this syntax properly, especially given that it is very sensitive; one wrong capitalization can lead to an inappropriate result!
* <b>Question:</b> This part is written in human language, so it should be easier for the model to understand (e.g., <i>"What is the total inventory value..."</i>). Since it states the intent of the user, the most challenging part here would be the correct understanding of the user's intent, though this should be manageable given the extensive pre-training of LLMs.
* <b>Query:</b> This part is again more difficult, both because the model first needs to understand the structure of SQL and then be able to produce error-free code. This is especially challenging because it is very sensitive to capitalization and punctuation (like the semicolon <code>;</code>).
</div>

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش دوم: آموزش مدل Encoder–Decoder (BART) (۱۵ نمره)</div>

<div dir="rtl" style="text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
<p style="line-height: 1.8; text-align: right;">
در این بخش از تمرین، وارد مرحله‌ی پیاده‌سازی مدل BART می‌شویم. پیش از شروع، لازم است به‌صورت مختصر و دقیق توضیح دهید که مدل BART چیست و چگونه کار می‌کند؛ به‌ویژه این‌که چرا معماری Encoder–Decoder آن برای وظایفی مانند Text-to-SQL مناسب است. انتظار می‌رود دانشجو به ساختار دو‌بخشی BART، نحوهٔ پردازش ورودی در انکودر و تولید خروجی در دیکودر اشاره کند و نشان دهد که این معماری برای نگاشت دنباله‌ای از کلمات (سؤال + schema) به دنباله‌ای دیگر (SQL) کاملاً مناسب است.
پس از توضیح مدل، باید قالب ورودی مناسبی طراحی کنید که در آن سؤال و schema به‌صورت یک رشتهٔ یکپارچه در اختیار مدل قرار گیرند. سپس یک Dataset اختصاصی برای BART بسازید که وظایفی مانند tokenize کردن ورودی، ساخت attention mask‌ها و آماده‌سازی SQL به عنوان خروجی هدف مدل را انجام دهد. مدل را <strong>حداقل یک ایپاک روی بیست هزار نمونه</strong> آموزش دهید و loss نهایی، زمان اجرا و هایپرپارامترهای اصلی را گزارش کنید.
در مرحلهٔ ارزیابی، باید عملکرد مدل را روی dev و test با دو معیار Raw Exact Match و Normalized Exact Match بسنجید.
از شما انتظار می‌رود که هر دو معیار را توضیح دهید:
Raw EM چگونه مقایسهٔ مستقیم دو رشته را انجام می‌دهد، چرا ممکن است برای SQL ناکافی باشد و Normalized EM چگونه با حذف تفاوت‌های سطحی (مثل فاصله‌ها، علامت‌ها و بزرگی یا کوچکی حروف) مقایسه‌ای عادلانه‌تر ارائه می‌دهد.
در پایان، پنج نمونهٔ تصادفی از dev انتخاب کنید و پرسش، خروجی مدل، SQL طلایی و نوع خطاها را تحلیل کنید.
<div dir="rtl" style="text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
نکته مهم:
برای پیاده‌سازی Raw EM می‌توانید از مقایسهٔ مستقیم رشته‌ها در پایتون استفاده کنید.
برای Normalized EM مجاز هستید از ابزارهایی مانند sqlparse برای فرمت‌بندی SQL و توابع سادهٔ پردازش متن جهت lowercase کردن و حذف فاصله‌های اضافی استفاده کنید، اما منطق مقایسه‌ی Normalized باید توسط خودتان نوشته شود.
</p>
</div>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
خروجی مورد انتظار این بخش، یک مدل BART آموزش‌دیده و ارزیابی‌شده است که بتواند از روی پرسش و ساختار پایگاه‌داده، کوئری SQL معتبر تولید کرده و معیارهای Raw EM و Normalized EM آن روی داده‌های dev و test گزارش شده باشد.
</p>

First let's create a funciton that concatinates the question and schema together, seperated by the end of sentence token.

In [8]:
def format_input(row):
    row['input_text'] = row['question'] + " </s> " + row['schema']
    return row

dataset = dataset.map(format_input)
print(dataset['train'][0])

{'question': 'What is the average severity of vulnerabilities found in the last quarter, grouped by month?', 'schema': 'CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT);', 'query': "SELECT DATE_FORMAT(timestamp, '%Y-%m') as month, AVG(severity) as avg_severity FROM vulnerabilities WHERE timestamp >= NOW() - INTERVAL 3 MONTH GROUP BY month;", 'input_text': 'What is the average severity of vulnerabilities found in the last quarter, grouped by month? </s> CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT);'}

Now let's load the model and tokenizer and prepare the dataset for BART. For the model we used facebook/bart-base for a balance between size/speed and capability (suggested by gemeni!)

As it turned out we should be replacing the padding toekns with -100 so the model skips them when evaluating (since we don't want the model to predict padding in the output sql!)

In [8]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

checkpoint = "facebook/bart-base"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

def preprocess_function(examples):
    inputs = [doc for doc in examples["input_text"]]
    model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")

    labels = tokenizer(text_target=examples["query"], max_length=128, truncation=True, padding="max_length")

    labels["input_ids"] = [
        [(l if l != tokenizer.pad_token_id else -100) for l in label] for label in labels["input_ids"]
    ]

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_dataset = dataset.map(preprocess_function, batched=True)
tokenized_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Now let's define the hyperparameters and trainer.

In [9]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
import time

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=3,
    predict_with_generate=True,
    fp16=True,
    logging_strategy="epoch",
    report_to="none"
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["dev"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

/tmp/ipython-input-3759121638.py:21: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

Now we can finally train the model and report the loss and main hyper parameters

In [10]:
start_time = time.time()
train_result = trainer.train()
end_time = time.time()

execution_time = end_time - start_time

print(f"Execution Time: {execution_time:.2f} seconds")
print(f"Final Loss: {train_result.training_loss:.4f}")

print("Loss per Epoch:")
for log in trainer.state.log_history:
    if "loss" in log and "epoch" in log:
        print(f"Epoch {log['epoch']}: Loss = {log['loss']:.4f}")

print("Hyperparameters:")
print(f"Learning Rate: {training_args.learning_rate}")
print(f"Batch Size: {training_args.per_device_train_batch_size}")
print(f"Weight Decay: {training_args.weight_decay}")
print(f"Epochs: {training_args.num_train_epochs}")

/usr/local/lib/python3.12/dist-packages/transformers/data/data_collator.py:740: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:253.)
  batch["labels"] = torch.tensor(batch["labels"], dtype=torch.int64)

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

Execution Time: 1881.26 seconds
Final Loss: 0.6705
Loss per Epoch:
Epoch 1.0: Loss = 0.9508
Epoch 2.0: Loss = 0.5681
Epoch 3.0: Loss = 0.4927
Hyperparameters:
Learning Rate: 2e-05
Batch Size: 16
Weight Decay: 0.01
Epochs: 3

As we can see we saw some improvements in the loss which is a good sign!

Now let's define the functions for Raw EM and Normalized EM.

In [11]:
import sqlparse

def compute_raw_em(prediction, reference):
    return prediction == reference

def normalize_sql(query):
    query = query.strip()
    while query.endswith(';'):
        query = query[:-1]

    query = sqlparse.format(query, reindent=True, keyword_case='upper', use_space_around_operators=True)

    query = " ".join(query.split())

    query = query.lower()

    return query

def compute_normalized_em(prediction, reference):
    norm_pred = normalize_sql(prediction)
    norm_ref = normalize_sql(reference)
    return norm_pred == norm_ref

Now let's validate the model on both dev and train sets. Also show 5 instances from dev set alongside model output and the gold output.

In [12]:
import torch
import random
from tqdm.auto import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def evaluate_dataset(split_name, dataset_key):
    print(f"Evaluating on {split_name}")
    predictions = []
    references = []

    dataloader = torch.utils.data.DataLoader(
        tokenized_dataset[dataset_key],
        batch_size=32,
        collate_fn=data_collator
    )

    model.eval()
    for batch in tqdm(dataloader):
        input_ids = batch.input_ids.to(device)
        attention_mask = batch.attention_mask.to(device)

        with torch.no_grad():
            outputs = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_length=128
            )

        decoded_preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)

        labels = batch.labels.cpu().numpy()
        labels = [[l if l != -100 else tokenizer.pad_token_id for l in label] for label in labels]
        decoded_refs = tokenizer.batch_decode(labels, skip_special_tokens=True)

        predictions.extend(decoded_preds)
        references.extend(decoded_refs)

    raw_em = sum(compute_raw_em(p, r) for p, r in zip(predictions, references)) / len(predictions)
    norm_em = sum(compute_normalized_em(p, r) for p, r in zip(predictions, references)) / len(predictions)

    print(f"{split_name} Raw EM: {raw_em:.4f}")
    print(f"{split_name} Normalized EM: {norm_em:.4f}")

evaluate_dataset("Dev Set", "dev")
evaluate_dataset("Test Set", "test")

print("5 Examples from Dev Set")
indices = random.sample(range(len(dataset['dev'])), 5)

for i in indices:
    example = dataset['dev'][i]
    inputs = tokenizer(example['input_text'], return_tensors="pt", truncation=True, max_length=512).to(device)

    with torch.no_grad():
        outputs = model.generate(**inputs, max_length=128)

    pred_sql = tokenizer.decode(outputs[0], skip_special_tokens=True)
    gold_sql = example['query']

    print(f"Question: {example['question']}")
    print(f"Gold SQL: {gold_sql}")
    print(f"Prediction: {pred_sql}")
    print(f"Raw Match: {compute_raw_em(pred_sql, gold_sql)}")
    print(f"Norm Match: {compute_normalized_em(pred_sql, gold_sql)}")
    print("---------------------------------------------")

Evaluating on Dev Set

  0%|          | 0/16 [00:00<?, ?it/s]

Dev Set Raw EM: 0.2180
Dev Set Normalized EM: 0.2220
Evaluating on Test Set

  0%|          | 0/63 [00:00<?, ?it/s]

Test Set Raw EM: 0.2115
Test Set Normalized EM: 0.2175
5 Examples from Dev Set
Question: What is the total CO2 emission for each factory in the Northern region by country?
Gold SQL: SELECT country, SUM(co2_emission) FROM factories JOIN country_regions ON factories.country = country_regions.country WHERE region = 'Northern' GROUP BY country;
Prediction: SELECT f.country, SUM(f.co2_emission) as total_co2 FROM factories f INNER JOIN country_regions c ON f.factory_id = c.id WHERE c.region = 'Northern';
Raw Match: False
Norm Match: False
---------------------------------------------
Question: Update all traffic violation fines to $150 in 'Downtown LA'
Gold SQL: UPDATE traffic_violations SET fine = 150 WHERE location = 'Downtown LA';
Prediction: UPDATE traffic_violations SET fine = 150 WHERE location = 'Downtown LA';
Raw Match: True
Norm Match: True
---------------------------------------------
Question: What is the total risk score for policyholders in New York?
Gold SQL: SELECT SUM(RiskScores.RiskScore) FROM RiskScores JOIN Policyholders ON RiskScores.PolicyholderID = Policyholders.PolicyholderID WHERE Policyholders.State = 'NY';
Prediction: SELECT SUM(RiskScore) FROM RiskScores WHERE State = 'NY';
Raw Match: False
Norm Match: False
---------------------------------------------
Question: Update the "EconomicDiversification" table to reflect that the budget for the 'Renewable Energy' project increased to $500,000
Gold SQL: UPDATE EconomicDiversification SET budget = 500000 WHERE project_name = 'Renewable Energy';
Prediction: UPDATE EconomicDiversification SET budget = 500000 WHERE project_name = 'Renewable Energy';
Raw Match: True
Norm Match: True
---------------------------------------------
Question: What is the average number of hours spent on open pedagogy projects by teachers from each department?
Gold SQL: SELECT d.department_name, AVG(t.hours_spent_on_projects) FROM departments d INNER JOIN teachers t ON d.department_id = t.department_id GROUP BY d.department_id;
Prediction: SELECT departments.department_name, AVG(teachers.hours_spent_on_projects) as avg_hours FROM departments INNER JOIN teachers ON department_id = teachers.teacher_id WHERE teachers.open_pedagogy = true GROUP BY departments.Department_name;
Raw Match: False
Norm Match: False
---------------------------------------------

<div dir='ltr' style='background:#fffbe6; font-family: sans-serif; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Analysis of Results:</b><br>

<b>⚠️ Note on Reproducibility:</b><br>
<i>The analysis below is based on the specific training run and examples generated at the time of writing. As the notebook may be re-run prior to final submission (and training involves stochastic elements), the exact metric values and specific generated examples in the final output cell may differ slightly from those discussed here.</i>
<hr style="border-top: 1px dashed #f0ad4e;">

<b>Performance Overview</b><br>
Looking at the results, the model achieved approximately <b>22% accuracy on the Dev set</b> and <b>21% on the Test set</b>. This is a solid baseline given that the model was fine-tuned on a limited dataset (20,000 samples) for only 3 epochs.

<b>Error Analysis</b><br>
An interesting observation is that the <b>Raw EM</b> and <b>Normalized EM</b> values are very close to each other. This suggests that the primary points of failure were structural and logical (the model didn't quite achieve the task or misunderstood it) rather than simple formatting issues or whitespace mismatches.

<b>Specific Failure Modes</b><br>
Among the failed examples, we see significant issues with <code>JOIN</code> operations. The model often produces invalid equality conditions by linking unrelated columns.

For example, in the <b>Risk Score</b> query:
<ul>
    <li><b>Gold:</b> ... <code>JOIN Policyholders ON RiskScores.PolicyholderID = Policyholders.PolicyholderID</code></li>
    <li><b>Prediction:</b> ... <code>JOIN RiskScores ON Policyholders.PolicyholderID = Riskscores.State</code></li>
</ul>

Here, the model attempts to join a <code>PolicyholderID</code> with a <code>State</code> column. While these concepts might be related in the real world (a person lives in a state), they are structurally incompatible as a join key! This indicates that while the model has understood the <i>syntax</i> of SQL (how to write a JOIN), it fails to fully grasp the <i>schema</i> or extract the correct column relationships from the input context.
</div>

<div dir='ltr' style='background:#fffbe6; font-family: sans-serif; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Answer:</b><br>
BART (Bidirectional and Auto-Regressive Transformers) is an encoder-decoder transformer model. We can think of it as the combination of a model like BERT (encoder-only) with GPT (decoder-only). These encoder-decoder models consist of two sections:

<b>1. The Encoder</b><br>
This part is the bidirectional component. It reads the entire input sequence (unlike decoder-only models that read one token at a time) and looks at the words/tokens to both the left and right of each token to attend to them. The goal for this stage is to produce useful encodings (similar to the contextual encodings of BERT) for the decoder section. This section uses self-attention as it is only paying attention to the input data.

<b>2. The Decoder</b><br>
The decoder part is an auto-regressive model, meaning it generates the output tokens (the SQL query in our case) one token at a time, from left to right. For generating the output, transformer blocks with cross-attention are used; the decoder looks at the encoder's output (which captures a full understanding of the input sequence), and based on that and the tokens it has previously generated, it assigns a probability to the next token. We then sample from it to generate the next token. (Basically, an augmented version of decoder-only networks).

<b>Why this structure suits Text-to-SQL:</b><br>
The reason why this structure is good for our task of Text-to-SQL is that, in general, the input and output tokens in encoder-decoder models can be vastly different in terms of size and domain (hence their main usage in translation). This is true for our case, too, where the input is a question written in human language and a schema in a structured format, but the output is the syntax of SQL!

Another advantage is that the <b>encoder</b> portion of the network is much better suited for handling the <b>schema</b>. You often need to look back and forth to properly understand how the database has been formatted (for example, how the parentheses are closed, which columns are in a specific table, etc.), and the bidirectional nature of the encoder allows it to form these complex relations better.

<hr style="border-top: 1px dashed #f0ad4e;">

<b>Raw EM vs. Normalized EM</b><br>

<b>1. Raw EM (Exact Match)</b><br>
This is the simplest way of checking the output of the model. With this method, we compare the generated output of the model with the gold output character by character (A == B). This implies that even a single extra space or mismatch in capitalization would result in a wrong answer. This is, of course, not ideal because there are many variations of SQL that differ only in spacing, punctuation, or capitalization. These variations do not make the command invalid but would be considered incorrect in this approach. Therefore, for SQL, it is best to avoid this and instead use the next method.

<b>2. Normalized EM</b><br>
Here, instead of comparing the results directly, we first "normalize" both the gold and generated output. Normalization refers to performing simple changes to the string that won't affect its functionality but will make the strings more similar. In our specific example, we make everything lowercase, remove extra spaces, and force spaces before and after operators. None of these changes affect the actual syntax or make a command invalid. This provides a fairer assessment of our model because it won't eliminate a result just because it has a simple difference that wouldn't affect functionality.
</div>

## <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش سوم: آموزش مدل Decoder-only (GPT-2) (۱۵ نمره)</div>

<div dir="rtl" style="text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
<p style="line-height: 1.8; text-align: right;">
در این بخش تسک Text-to-SQL را با معماری GPT-2 پیاده‌سازی می‌کنید. ابتدا قالب ورودی مناسب برای مدل‌های decoder-only طراحی کنید، به‌طوری‌که پرسش و schema به‌صورت یک prefix مشخص (مانند question: … schema: … SQL:) به مدل داده شوند و مدل ادامه آن را به‌صورت SQL تولید کند. سپس یک Dataset مخصوص causal LM بسازید که full sequence (prefix + gold SQL + EOS) را تولید کرده و بخش prefix را در برچسب‌ها mask کند. مدل GPT-2 را یک epoch آموزش دهید و loss و زمان اجرا را گزارش کنید. هنگام ارزیابی، prefix را از خروجی حذف کنید و تنها SQL تولیدشده را بسنجید. معیارهای Raw EM و Normalized EM را روی dev و test گزارش کرده و ۵ نمونه از خروجی مدل را بررسی و تحلیل کنید.
</p>
</div>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
خروجی مورد انتظار این بخش، یک مدل GPT-2 آموزش‌دیده و ارزیابی‌شده است که با استفاده از قالب ورودی مبتنی بر prefix قادر به تولید SQL بوده و معیارهای Raw EM و Normalized EM آن روی مجموعه‌های dev و test به‌درستی محاسبه و گزارش شده باشند.
</p>

First let's combine the question and schema into one column named prefix (question: ... schema: ...)

In [30]:
import gc
import torch

del model
del trainer
del tokenized_dataset
del data_collator

NameError: name 'model' is not defined

In [36]:
gc.collect()
torch.cuda.empty_cache()

In [9]:
def format_gpt2_data(row):
    row['prefix'] = f"question: {row['question']} schema: {row['schema']} SQL: "
    return row

gpt2_dataset = dataset.map(format_gpt2_data)
print(gpt2_dataset['train'][0])

{'question': 'What is the average severity of vulnerabilities found in the last quarter, grouped by month?', 'schema': 'CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT);', 'query': "SELECT DATE_FORMAT(timestamp, '%Y-%m') as month, AVG(severity) as avg_severity FROM vulnerabilities WHERE timestamp >= NOW() - INTERVAL 3 MONTH GROUP BY month;", 'input_text': 'What is the average severity of vulnerabilities found in the last quarter, grouped by month? </s> CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT);', 'prefix': 'question: What is the average severity of vulnerabilities found in the last quarter, grouped by month? schema: CREATE TABLE vulnerabilities(id INT, timestamp TIMESTAMP, severity FLOAT); SQL: '}

We don't really care about how the model predicts the words in prefix, so we will make a dataset for GPT-2 (which is a casual LM) that is like (prefix + gold SQL + EOS) and mask the prefix so it wouldn't be validated.

In [10]:
from transformers import AutoTokenizer

tokenizer_gpt = AutoTokenizer.from_pretrained("gpt2")
tokenizer_gpt.pad_token = tokenizer_gpt.eos_token

def preprocess_gpt2_function(examples):
    model_inputs = {"input_ids": [], "attention_mask": [], "labels": []}

    for prefix, query in zip(examples["prefix"], examples["query"]):
        prefix_ids = tokenizer_gpt(prefix, add_special_tokens=False)["input_ids"]
        query_ids = tokenizer_gpt(query + tokenizer_gpt.eos_token, add_special_tokens=False)["input_ids"]

        full_ids = prefix_ids + query_ids
        full_labels = [-100] * len(prefix_ids) + query_ids

        if len(full_ids) > 512:
            full_ids = full_ids[:512]
            full_labels = full_labels[:512]

        model_inputs["input_ids"].append(full_ids)
        model_inputs["attention_mask"].append([1] * len(full_ids))
        model_inputs["labels"].append(full_labels)

    return model_inputs

tokenized_gpt2_dataset = gpt2_dataset.map(
    preprocess_gpt2_function,
    batched=True,
    remove_columns=gpt2_dataset["train"].column_names
)

It turns out we also need to make all the sequences the same lenght, so we will fix that in the next section.

In [12]:
from transformers import DataCollatorForLanguageModeling, DataCollatorForSeq2Seq

data_collator_gpt = DataCollatorForSeq2Seq(tokenizer=tokenizer_gpt, padding=True)

Now let's define the hyper parameters and load the model.

In [13]:
from transformers import AutoModelForCausalLM, TrainingArguments, Trainer
import time

model_gpt = AutoModelForCausalLM.from_pretrained("gpt2")

training_args = TrainingArguments(
    output_dir="./results_gpt",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=1,
    fp16=True,
    logging_strategy="epoch",
    report_to="none"
)

trainer = Trainer(
    model=model_gpt,
    args=training_args,
    train_dataset=tokenized_gpt2_dataset["train"],
    eval_dataset=tokenized_gpt2_dataset["dev"],
    tokenizer=tokenizer_gpt,
    data_collator=data_collator_gpt,
)

/tmp/ipython-input-1114812166.py:20: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

And finally train the model.

In [14]:
start_time = time.time()
train_result = trainer.train()
end_time = time.time()

execution_time = end_time - start_time

print(f"Execution Time: {execution_time:.2f} seconds")
print(f"Final Loss: {train_result.training_loss:.4f}")

print("Loss per Epoch:")
for log in trainer.state.log_history:
    if "loss" in log and "epoch" in log:
        print(f"Epoch {log['epoch']}: Loss = {log['loss']:.4f}")

print("Hyperparameters:")
print(f"Learning Rate: {training_args.learning_rate}")
print(f"Batch Size: {training_args.per_device_train_batch_size}")
print(f"Weight Decay: {training_args.weight_decay}")
print(f"Epochs: {training_args.num_train_epochs}")

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Execution Time: 718.97 seconds
Final Loss: 0.8382
Loss per Epoch:
Epoch 1.0: Loss = 0.8382
Hyperparameters:
Learning Rate: 2e-05
Batch Size: 16
Weight Decay: 0.01
Epochs: 1

Now let's re-define the EM functions (I ran out of VRAM so the notebook had to be restarted)

In [15]:
import sqlparse

def compute_raw_em(prediction, reference):
    return prediction == reference

def normalize_sql(query):
    query = query.strip()
    while query.endswith(';'):
        query = query[:-1]

    query = sqlparse.format(query, reindent=True, keyword_case='upper', use_space_around_operators=True)

    query = " ".join(query.split())

    query = query.lower()

    return query

def compute_normalized_em(prediction, reference):
    norm_pred = normalize_sql(prediction)
    norm_ref = normalize_sql(reference)
    return norm_pred == norm_ref

And finally let's evalute the model.

In [17]:
import torch
import random
from tqdm.auto import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_gpt.to(device)
tokenizer_gpt.padding_side = "left"

def evaluate_gpt_dataset(split_name, dataset_key):
    print(f"Evaluating on {split_name}")
    predictions = []
    references = []

    data = gpt2_dataset[dataset_key]
    batch_size = 32

    for i in tqdm(range(0, len(data), batch_size)):
        batch_prefixes = data[i:i+batch_size]['prefix']
        batch_queries = data[i:i+batch_size]['query']

        inputs = tokenizer_gpt(batch_prefixes, return_tensors="pt", padding=True, truncation=True, max_length=512).to(device)

        with torch.no_grad():
            outputs = model_gpt.generate(
                **inputs,
                max_new_tokens=128,
                pad_token_id=tokenizer_gpt.eos_token_id
            )

        decoded_preds = tokenizer_gpt.batch_decode(outputs, skip_special_tokens=True)

        for decoded_text, prefix in zip(decoded_preds, batch_prefixes):
            pred_sql = decoded_text[len(prefix):].strip()
            predictions.append(pred_sql)

        references.extend(batch_queries)

    raw_em = sum(compute_raw_em(p, r) for p, r in zip(predictions, references)) / len(predictions)
    norm_em = sum(compute_normalized_em(p, r) for p, r in zip(predictions, references)) / len(predictions)

    print(f"{split_name} Raw EM: {raw_em:.4f}")
    print(f"{split_name} Normalized EM: {norm_em:.4f}")

evaluate_gpt_dataset("Dev Set", "dev")
evaluate_gpt_dataset("Test Set", "test")

print("5 Examples from Dev Set")
indices = random.sample(range(len(gpt2_dataset['dev'])), 5)

for i in indices:
    example = gpt2_dataset['dev'][i]
    prefix = example['prefix']
    inputs = tokenizer_gpt(prefix, return_tensors="pt", truncation=True, max_length=512).to(device)

    with torch.no_grad():
        outputs = model_gpt.generate(**inputs, max_new_tokens=128, pad_token_id=tokenizer_gpt.eos_token_id)

    full_output = tokenizer_gpt.decode(outputs[0], skip_special_tokens=True)
    pred_sql = full_output[len(prefix):].strip()
    gold_sql = example['query']

    print(f"Question: {example['question']}")
    print(f"Gold SQL: {gold_sql}")
    print(f"Prediction: {pred_sql}")
    print(f"Raw Match: {compute_raw_em(pred_sql, gold_sql)}")
    print(f"Norm Match: {compute_normalized_em(pred_sql, gold_sql)}")
    print("---------------------------------------------")

Evaluating on Dev Set

  0%|          | 0/16 [00:00<?, ?it/s]

Dev Set Raw EM: 0.0800
Dev Set Normalized EM: 0.0840
Evaluating on Test Set

  0%|          | 0/63 [00:00<?, ?it/s]

Test Set Raw EM: 0.0755
Test Set Normalized EM: 0.0795
5 Examples from Dev Set
Question: What is the total CO2 emission for each factory in the Northern region by country?
Gold SQL: SELECT country, SUM(co2_emission) FROM factories JOIN country_regions ON factories.country = country_regions.country WHERE region = 'Northern' GROUP BY country;
Prediction: SELECT country, COUNT(*) as total_co2_emission FROM factories GROUP BY country;
Raw Match: False
Norm Match: False
---------------------------------------------
Question: Update all traffic violation fines to $150 in 'Downtown LA'
Gold SQL: UPDATE traffic_violations SET fine = 150 WHERE location = 'Downtown LA';
Prediction: UPDATE traffic_violations SET fine = 150 WHERE location = 'Downtown LA';
Raw Match: True
Norm Match: True
---------------------------------------------
Question: What is the total risk score for policyholders in New York?
Gold SQL: SELECT SUM(RiskScores.RiskScore) FROM RiskScores JOIN Policyholders ON RiskScores.PolicyholderID = Policyholders.PolicyholderID WHERE Policyholders.State = 'NY';
Prediction: SELECT SUM(RiskScore) FROM RiskScores WHERE State = 'NY';
Raw Match: False
Norm Match: False
---------------------------------------------
Question: Update the "EconomicDiversification" table to reflect that the budget for the 'Renewable Energy' project increased to $500,000
Gold SQL: UPDATE EconomicDiversification SET budget = 500000 WHERE project_name = 'Renewable Energy';
Prediction: UPDATE EconomicDiversification SET budget = 500000 WHERE project_name = 'Renewable Energy';
Raw Match: True
Norm Match: True
---------------------------------------------
Question: What is the average number of hours spent on open pedagogy projects by teachers from each department?
Gold SQL: SELECT d.department_name, AVG(t.hours_spent_on_projects) FROM departments d INNER JOIN teachers t ON d.department_id = t.department_id GROUP BY d.department_id;
Prediction: SELECT department_name, AVG(hours_spent_on_projects) as avg_hours_spent_on_projects FROM teachers INNER JOIN teachers ON teachers.department_id = teachers.department_id WHERE teachers.teacher_name = 'Mathematics' AND teachers.teacher_name = 'Ms. Johnson';
Raw Match: False
Norm Match: False
---------------------------------------------

<div dir='ltr' style='background:#f2f0f5; font-family: sans-serif; border:1px dashed #6d28d9; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Analysis of GPT-2 Results:</b><br>

<b>Performance Overview</b><br>
As we can see, the GPT-2 model did not perform very well. It only achieved about <b>8% accuracy</b> on both the Dev and Test sets, which is quite low compared to BART and low in general. This suggests that fine-tuning a standard GPT-2 model by simply concatenating everything into a single sequence is not sufficient to make the model generate complex SQL commands reliably.

The fact that we only trained the model for <b>1 epoch</b> could also be a major factor here, but this was a specific requirement of the assignment and out of our control.

<b>Error Analysis</b><br>
Looking at the incorrect predictions, we can categorize the errors into two main types:

<b>1. Oversimplification</b><br>
The model often takes the "easy way out." For example, if a question requires joining two tables, the model tries to find everything in the first table, even if the required columns don't exist there. This leads directly to the second issue.

<b>2. Hallucination</b><br>
This is a well-known issue with models like GPT. Since these are "creative" models designed to act as Causal Language Models, they always prioritize producing a fluent answer. When the model cannot determine the correct logic from the schema, it simply "makes something up," which obviously leads to incorrect outputs.

<b>Specific Examples:</b>

<ul>
    <li><b>The "Risk Score" Failure (Schema Linking):</b><br>
    <i>The Goal:</i> The model needed to filter policyholders by "State". This required joining the <code>RiskScores</code> table with the <code>Policyholders</code> table.<br>
    <i>The Error:</i> GPT-2 wrote <code>WHERE State = 'NY'</code> directly on the <code>RiskScores</code> table. It failed to realize (or forgot) that "State" is not a column in "RiskScores". It failed to link the tables correctly.
    </li>
    <br>
    <li><b>The "Open Pedagogy" Failure (Hallucination):</b><br>
    <i>The Goal:</i> Calculate average hours for departments.<br>
    <i>The Error:</i> The model suddenly added <code>WHERE teachers.teacher_name = 'Mathematics'</code>. The user never asked for Mathematics! The model just "dreamed up" a likely-sounding filter because it has seen similar patterns in its pre-training data.
    </li>
</ul>
</div>

<div dir='ltr' style='background:#fffbe6; font-family: sans-serif; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Answer:</b><br>
GPT-2 is a <b>Decoder-Only</b> transformer model. Unlike Encoder-Only models (like BERT) or Encoder-Decoder models (like BART), GPT-2 is fundamentally <b>autoregressive</b>. This means the network sees the input sequence one token at a time and generates output tokens sequentially from left to right.

<b>Key Architectural Feature: Masked Self-Attention</b><br>
In this structure, the model uses masked self-attention. This constraint ensures that when the model is processing a specific token, it can only "attend" to (look at) the tokens that came <i>before</i> it. It cannot see future tokens.

<b>Applicability to Text-to-SQL:</b><br>
The reason this structure can work for Text-to-SQL—even though it wasn't explicitly built for translation tasks—is that we can frame almost any NLP task as a <b>Sequence Completion</b> (Next-Word Prediction) problem. By formatting the input as a prompt (Context + Question), we can expect the model to "complete" the pattern by generating the appropriate SQL command.

<b>Potential Points of Failure:</b><br>
However, this architecture introduces specific risks for this task:
<ul>
    <li><b>Lack of Bidirectional Context:</b> When reading a database schema, one often needs to look "back and forth" to understand relationships (e.g., how a foreign key in a later table relates to a primary key seen earlier). A unidirectional decoder struggles with this because it cannot attend to "future" tokens to clarify the meaning of current ones.</li>
    <li><b>Single Stream Processing:</b> Unlike Encoder-Decoder models, which explicitly separate the input (human language) and output (SQL) into different processing stages, Decoder-only models treat everything as a single continuous stream. This lack of separation can make them less robust for strict "translation" tasks where the input and output domains are highly dissimilar.</li>
</ul>
</div>

### <div style="text-align: center; direction: rtl; font-family: Vazir;">بخش چهارم: مقایسه و تحلیل نهایی (۱۰ نمره)</div>

<div dir="rtl" style="text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
<p style="line-height: 1.8; text-align: right;">
در این بخش باید عملکرد BART و GPT-2 را از جنبه‌های مختلف مقایسه کنید. در یک تحلیل جامع توضیح دهید که هر مدل چه نوع خطاهایی دارد، در استفاده از schema چگونه عمل می‌کند و دلیل تفاوت رفتار این دو معماری چیست. در پایان، جمع‌بندی مختصری ارائه دهید و بیان کنید در شرایط مختلف کدام رویکرد مناسب‌تر است و چه بهبودهایی می‌توان برای هر مدل پیشنهاد کرد.</p>
</div>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
خروجی مورد انتظار این بخش، یک تحلیل جامع و مقایسه‌محور است که در آن عملکرد، خطاها، نقاط قوت و ضعف دو مدل BART و GPT-2 بر اساس معیارهای ارزیابی، نمونه‌های تولیدی و تفاوت‌های معماری به‌طور دقیق بررسی و جمع‌بندی شده باشد.
</p>

In [ ]:
# Unfortunately I could not have both models on google colab at the same time due to memory limitations.
# So we cannot compare their performance directly here and we will rely on previous results.

<div dir='ltr' style='background:#fffbe6; font-family: sans-serif; border:1px dashed #f0ad4e; padding:12px; border-radius:8px; color:#111; text-align: left;'>
✍️ <b>Answer:</b><br>

<b>Performance Comparison</b><br>
There is a clear difference in performance between the two architectures. While BART achieved an approximate <b>22% accuracy</b>, GPT-2 reached only <b>8%</b>. This demonstrates the superiority of BART and the Encoder-Decoder architecture in general for this specific Text-to-SQL task.

<b>Architectural Analysis</b><br>
The main reason for this performance gap can be traced back to the structural differences:
<ul>
    <li><b>BART (Encoder-Decoder):</b> The encoder reads the entire input sequence simultaneously (bidirectional attention). This allows the model to "see" the entire schema at once and understand the structure of the database <i>before</i> attempting to generate the SQL. Additionally, the separation of input (natural language) and output (SQL syntax) is advantageous for translation-like tasks.</li>
    <li><b>GPT-2 (Decoder-Only):</b> This model reads strictly from left to right (masked self-attention). By the time it begins generating the SQL, it may lose focus on the specific details of the schema provided earlier in the prompt. Because it lacks the ability to attend "globally" like an encoder, it treats the schema more as a preceding sentence in a story rather than a strict blueprint for generation.</li>
</ul>

<b>Error Analysis</b><br>
This difference is further highlighted by the types of errors generated:
<ul>
    <li><b>BART:</b> Errors were mostly <b>structural or logical</b>. The outputs were often close to the correct answer; the model attempted the correct logic but might select the wrong key for a JOIN, indicating it understood <i>how</i> SQL works but struggled with specific schema linking.</li>
    <li><b>GPT-2:</b> Errors were characterized by <b>hallucinations and oversimplifications</b>. It often ignored the need for JOINs, trying to find all data in a single table even when impossible. When that failed, it often generated column names or values that did not exist, prioritizing fluency ("sounding good") over correctness.</li>
</ul>

<b>Conclusion & Future Improvements</b><br>
For a Supervised Fine-Tuning (SFT) task on a relatively small dataset, <b>Encoder-Decoder models like BART are superior</b> due to their ability to better comprehend the input schema.

To improve performance:
<ul>
    <li><b>For BART:</b> We could explicitly highlight foreign keys or schema relationships in the input string to help the model with schema linking.</li>
    <li><b>For GPT-2:</b> A larger model, more training data, and <b>few-shot prompting</b> (showing examples of valid SQL in the prompt) would likely be necessary to guide the model away from hallucinations.</li>
</ul>
</div>

# <h1 style="text-align: right;">**نکات مهم و قوانین تحویل**</h1>


<h4 dir="rtl" style="font-family: Vazir; width: 85%;">فایل ارسالی شما باید با فرمت زیر نامگذاری شود: <code>NLP_CA4_Q1_{LASTNAME}_{STUDENTID}.ipynb</code></h4>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">نحوه انجام تمرین:</h4>
<ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
  <li>سلول‌های کد با برچسب <code>WRITE YOUR CODE HERE</code> را تکمیل کنید.</li>
  <li>برای پاسخ‌های متنی، متن <code>{{پاسخ_خود_را_اینجا_بنویسید}}</code> را با پاسخ خود جایگزین کنید.</li>
</ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">صداقت علمی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;"> <li>ما نوت‌بوک‌های تعداد مشخصی از دانشجویان که به صورت تصادفی انتخاب می‌شوند، بررسی خواهیم کرد. این بررسی‌ها اطمینان حاصل می‌کنند که کدی که نوشتید واقعاً پاسخ‌های موجود در نوت‌بوک شما را تولید می‌کند. اگر پاسخ‌های صحیح را در نوت‌بوک خود بدون کدی که واقعاً آن پاسخ‌ها را تولید کند تحویل دهید، این یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> <li>ما همچنین بررسی‌های خودکاری را برای تشخیص سرقت علمی در نوت‌بوک‌های کولب انجام خواهیم داد. کپی کردن کد از دیگران نیز یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> </ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">توضیحات تکمیلی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
<li>
خوانایی و دقت بررسی‌ها در گزارش نهایی از اهمیت ویژه‌ای برخوردار است. به تمرین‌هایی که به صورت کاغذی تحویل داده شوند یا به صورت عکس در سایت بارگذاری شوند، ترتیب اثری داده نخواهد شد.</li>
<li>
 همه‌ی کدهای پیوست گزارش بایستی قابلیت اجرای مجدد داشته باشند. در صورتی که برای اجرا مجدد آن‌ها نیاز به تنظیمات خاصی می‌باشد، بایستی تنظیمات مورد نیاز را نیز در گزارش خود ذکر کنید.  دقت کنید که  تمامی کدها باید توسط شما اجرا شده باشند و نتایج اجرا در فایل کدهای ارسالی مشخص باشد. به کدهایی که نتایج اجرای آن‌ها در فایل ارسالی مشخص نباشد نمره‌ای تعلق نمی‌گیرد.
</li>
<li>توجه کنید این تمرین باید به صورت تک‌نفره انجام شود و پاسخ‌های ارائه شده باید نتیجه فعالیت فرد نویسنده باشد (همفکری و به اتفاق هم نوشتن تمرین نیز ممنوع است). در صورت مشاهده
 تشابه به همه افراد مشارکت‌کننده، نمره تمرین صفر و به استاد گزارش می‌گردد.
 </li>

 <li>
لطفاً تمامی پاسخ‌های متنی خود را با <b>فونت وزیر (Vazir)</b> و به‌صورت <b>راست‌چین</b> بنویسید.  
از استفاده از فونت‌های پیش‌فرض خودداری کنید تا ظاهر نوت‌بوک شما یک‌دست و خوانا باشد.  
در بخش‌های تشریحی، سعی کنید پاسخ‌ها را کامل، منسجم و با رعایت نگارش فارسی بنویسید.  
همچنین، به چینش تمیز سلول‌ها و اجرای درست کدها توجه کنید تا تمرین شما با فرمت خواسته‌شده و استاندارد ارائه شود.
</li>
 <li>برای مطالعه بیشتر درباره‌ی فرمت Markdown می‌توانید از <a href="https://github.com/tajaddini/Persian-Markdown/blob/master/learn-MD.md">این لینک</a> مطالعه کنید.
 </li>
 </ul>
    

 </div>